Update test_notebooks.yml
added yaml logic - needs work

diff --git a/.github/workflows/test_notebooks.yml b/.github/workflows/test_notebooks.yml
--- a/.github/workflows/test_notebooks.yml
+++ b/.github/workflows/test_notebooks.yml
@@ -42,3 +42,33 @@ jobs:
           rsync -aP --exclude '**.png' --exclude '**.gif' dummy_repo/pynest/examples temp_examples
           # find nest-simulator/pynest/examples/ -iname "*.py" -exec cp --parents \{\} ./temp_examples \;
 
+      - name: "Install Python dependencies"
+        run: |
+          python -m pip install --upgrade pip setuptools
+          python -m pip install ipykernel jupytext yq
+      - name: "Convert to notebooks and set kernel"
+        run: |
+          YAML_FILE="pynest_examples_metadata.yaml"
+          # Check if the YAML file exists
+          if [ ! -f "$YAML_FILE" ]; then
+            echo "YAML file not found: $YAML_FILE"
+          exit 1
+          fi
+
+          # Use yq to extract Python files and execute jupytext
+          yq eval '.directories[].conver2notebooks[]' "$YAML_FILE" | while read -r file; do
+          echo "Converting $file to notebook..."
+          # jupytext --to notebook "$file"
+          # done
+          exit 0
+          # jupytext --to notebook  $(find temp_examples -iname "*.py")
+          python -m ipykernel install --user --name "$NAME" --display-name "$DISPLAY_NAME"
+          jupytext --set-kernel "$NAME"  $(find temp_examples -iname "*.ipynb")
+
+      - name: Commit and push changes
+        run: |
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          git add temp_examples/
+          git commit -m "Add Python files from nest v${NEST_VERSION}_rc${rc_number}"
+          git push origin HEAD
